### PR TITLE
Added bower support; remove version number from filenames.

### PR DESCRIPTION
**Pull request by mehcode**
Added bower support. Version numbers shouldn't be in the filenames and we should use git tags to distinguish the versions.

A question; why is the main branch `gh-pages`? Github is going to be publishing this and being weird about it.

After this is merged we can register it in bower.

### CODE REVIEW

**Comment by paulmillr** [comment]
I was thinking of making the repo subdirectory of chaplinjs.org like `chaplinjs.org/downloads/amd/chaplin.js` but then I realised gh can be host for us

**Comment by paulmillr** [comment]
btw this means bower will contain amd-only stuff.

we definitely need to provide universal build.

**Comment by mehcode** [comment]
> btw this means bower will contain amd-only stuff.

The `main` key in the component.json for bower only determines what tools like `grunt-bower-hooks` will grab. Bower will still download the entire repository as we don't have a `.bowerignore` file (and it hasn't been implemented in bower yet).

**Comment by mehcode** [comment]
And we actually would be waiting on https://github.com/twitter/bower/issues/192 because this repository is called something generic like downloads, before we can register it.

**Pull request merged**
